/**
 * O‘zbekiston viloyatlari bo‘yicha tuman va shaharlar (sozlamalar / profil tanlovi).
 * id — saqlash uchun; label — ko‘rinish uchun.
 */
export const UZ_VILOYAT_DISTRICTS = {
  andijon: [
    { id: 'andijon_sh', label: 'Andijon shahri' },
    { id: 'xonobod', label: 'Xonobod shahri' },
    { id: 'asaka', label: 'Asaka tumani' },
    { id: 'baliqchi', label: 'Baliqchi tumani' },
    { id: 'boz', label: "Bo'z tumani" },
    { id: 'buloqboshi', label: 'Buloqboshi tumani' },
    { id: 'izboskan', label: 'Izboskan tumani' },
    { id: 'jalolquduq', label: 'Jalolquduq tumani' },
    { id: 'marhamat', label: 'Marhamat tumani' },
    { id: 'oltinkol', label: "Oltinko'l tumani" },
    { id: 'paxtaobod', label: 'Paxtaobod tumani' },
    { id: 'qorgontepa', label: "Qo'rg'ontepa tumani" },
    { id: 'shahrixon', label: 'Shahrixon tumani' },
    { id: 'ulugnor', label: "Ulug'nor tumani" },
    { id: 'xojaobod', label: "Xo'jaobod tumani" },
  ],
  buxoro: [
    { id: 'buxoro_sh', label: 'Buxoro shahri' },
    { id: 'kogon_sh', label: 'Kogon shahri' },
    { id: 'alat', label: 'Alat tumani' },
    { id: 'buxoro_t', label: 'Buxoro tumani' },
    { id: 'gijduvon', label: "G'ijduvon tumani" },
    { id: 'jondor', label: 'Jondor tumani' },
    { id: 'kogon_t', label: 'Kogon tumani' },
    { id: 'olot', label: 'Olot tumani' },
    { id: 'paxtakor', label: 'Paxtakor tumani' },
    { id: 'qorakol', label: "Qorako'l tumani" },
    { id: 'qorovulbozor', label: 'Qorovulbozor tumani' },
    { id: 'romitan', label: 'Romitan tumani' },
    { id: 'shofirkon', label: 'Shofirkon tumani' },
    { id: 'vobkent', label: 'Vobkent tumani' },
  ],
  fargona: [
    { id: 'fargona_sh', label: "Farg'ona shahri" },
    { id: 'margilon', label: "Marg'ilon shahri" },
    { id: 'qoqon', label: "Qo'qon shahri" },
    { id: 'quvasoy', label: 'Quvasoy shahri' },
    { id: 'bagdod', label: "Bag'dod tumani" },
    { id: 'beshariq', label: 'Beshariq tumani' },
    { id: 'buvayda', label: "Buvayda tumani" },
    { id: 'dangara', label: "Dang'ara tumani" },
    { id: 'furqat', label: 'Furqat tumani' },
    { id: 'fargona_t', label: "Farg'ona tumani" },
    { id: 'ozbekiston', label: "O'zbekiston tumani" },
    { id: 'oltiariq', label: "Oltiariq tumani" },
    { id: 'qoshtepa', label: "Qo'shtepa tumani" },
    { id: 'rishton', label: 'Rishton tumani' },
    { id: 'sox', label: "So'x tumani" },
    { id: 'toshloq', label: 'Toshloq tumani' },
    { id: 'uchkoprik', label: "Uchko'prik tumani" },
    { id: 'uzun', label: 'Uzun tumani' },
    { id: 'yangiobod', label: 'Yangiobod tumani' },
    { id: 'yozyovon', label: 'Yozyovon tumani' },
  ],
  jizzax: [
    { id: 'jizzax_sh', label: 'Jizzax shahri' },
    { id: 'gagarin', label: 'Gagarin shahri' },
    { id: 'arnasoy', label: 'Arnasoy tumani' },
    { id: 'baxmal', label: 'Baxmal tumani' },
    { id: 'dostlik', label: "Do'stlik tumani" },
    { id: 'forish', label: 'Forish tumani' },
    { id: 'gallaorol', label: "G'allaorol tumani" },
    { id: 'jizzax_t', label: 'Jizzax tumani' },
    { id: 'mirzachol', label: "Mirzacho'l tumani" },
    { id: 'paxtakor', label: 'Paxtakor tumani' },
    { id: 'yangiobod', label: 'Yangiobod tumani' },
    { id: 'zafarobod', label: 'Zafarobod tumani' },
    { id: 'zarbdor', label: 'Zarbdor tumani' },
    { id: 'zomin', label: 'Zomin tumani' },
  ],
  xorazm: [
    { id: 'urganch_sh', label: 'Urganch shahri' },
    { id: 'xiva_sh', label: 'Xiva shahri' },
    { id: 'bogot', label: "Bog'ot tumani" },
    { id: 'gurlan', label: 'Gurlan tumani' },
    { id: 'xonqa', label: 'Xonqa tumani' },
    { id: 'xiva_t', label: 'Xiva tumani' },
    { id: 'qoshkopir', label: "Qo'shko'pir tumani" },
    { id: 'shovot', label: 'Shovot tumani' },
    { id: 'urganch_t', label: 'Urganch tumani' },
    { id: 'yangiariq', label: 'Yangiariq tumani' },
    { id: 'yangibozor', label: 'Yangibozor tumani' },
  ],
  namangan: [
    { id: 'namangan_sh', label: 'Namangan shahri' },
    { id: 'chortoq', label: 'Chortoq tumani' },
    { id: 'chust', label: 'Chust tumani' },
    { id: 'kosonsoy', label: 'Kosonsoy tumani' },
    { id: 'mingbuloq', label: 'Mingbuloq tumani' },
    { id: 'namangan_t', label: 'Namangan tumani' },
    { id: 'norin', label: 'Norin tumani' },
    { id: 'pop', label: 'Pop tumani' },
    { id: 'toraqorgon', label: "To'raqo'rg'on tumani" },
    { id: 'uchqorgon', label: "Uchqo'rg'on tumani" },
    { id: 'uychi', label: 'Uychi tumani' },
    { id: 'yangiqorgon', label: "Yangiqo'rg'on tumani" },
  ],
  navoiy: [
    { id: 'navoiy_sh', label: 'Navoiy shahri' },
    { id: 'zarafshon', label: 'Zarafshon shahri' },
    { id: 'konimex', label: 'Konimex tumani' },
    { id: 'karmana', label: 'Karmana tumani' },
    { id: 'navbahor', label: 'Navbahor tumani' },
    { id: 'navoiy_t', label: 'Navoiy tumani' },
    { id: 'nurota', label: 'Nurota tumani' },
    { id: 'qiziltepa', label: 'Qiziltepa tumani' },
    { id: 'tamdi', label: 'Tamdi tumani' },
    { id: 'tomdi', label: 'Tomdi tumani' },
    { id: 'uchquduq', label: "Uchquduq tumani" },
    { id: 'xatirchi', label: 'Xatirchi tumani' },
  ],
  qashqadaryo: [
    { id: 'qarshi_sh', label: 'Qarshi shahri' },
    { id: 'shahrisabz_sh', label: 'Shahrisabz shahri' },
    { id: 'chiroqchi', label: 'Chiroqchi tumani' },
    { id: 'dehqonobod', label: 'Dehqonobod tumani' },
    { id: 'guzor', label: "G'uzor tumani" },
    { id: 'qamashi', label: 'Qamashi tumani' },
    { id: 'qarshi_t', label: 'Qarshi tumani' },
    { id: 'kasbi', label: 'Kasbi tumani' },
    { id: 'kitob', label: 'Kitob tumani' },
    { id: 'koson', label: 'Koson tumani' },
    { id: 'muborak', label: 'Muborak tumani' },
    { id: 'nishon', label: 'Nishon tumani' },
    { id: 'shahrisabz_t', label: 'Shahrisabz tumani' },
    { id: 'yakkabog', label: "Yakkabog' tumani" },
  ],
  samarqand: [
    { id: 'samarqand_sh', label: 'Samarqand shahri' },
    { id: 'kattaqorgon_sh', label: "Kattaqo'rg'on shahri" },
    { id: 'bulungur', label: "Bulung'ur tumani" },
    { id: 'ishtixon', label: 'Ishtixon tumani' },
    { id: 'jomboy', label: 'Jomboy tumani' },
    { id: 'kattaqorgon_t', label: "Kattaqo'rg'on tumani" },
    { id: 'narpay', label: 'Narpay tumani' },
    { id: 'nurabod', label: 'Nurabod tumani' },
    { id: 'oqdaryo', label: "Oqdaryo tumani" },
    { id: 'payariq', label: 'Payariq tumani' },
    { id: 'pastdargom', label: "Pastdarg'om tumani" },
    { id: 'paxtachi', label: 'Paxtachi tumani' },
    { id: 'qorgontepa', label: "Qo'rg'ontepa tumani" },
    { id: 'samarqand_t', label: 'Samarqand tumani' },
    { id: 'toyloq', label: 'Toyloq tumani' },
    { id: 'urgut', label: 'Urgut tumani' },
  ],
  sirdaryo: [
    { id: 'guliston_sh', label: 'Guliston shahri' },
    { id: 'shirin', label: 'Shirin shahri' },
    { id: 'yangiyer', label: 'Yangiyer shahri' },
    { id: 'boyovut', label: 'Boyovut tumani' },
    { id: 'guliston_t', label: 'Guliston tumani' },
    { id: 'mirzaobod', label: 'Mirzaobod tumani' },
    { id: 'oqoltin', label: 'Oqoltin tumani' },
    { id: 'sardoba', label: 'Sardoba tumani' },
    { id: 'sayxunobod', label: 'Sayxunobod tumani' },
    { id: 'sirdaryo_t', label: 'Sirdaryo tumani' },
    { id: 'xavos', label: 'Xavos tumani' },
  ],
  surxondaryo: [
    { id: 'termiz_sh', label: 'Termiz shahri' },
    { id: 'angor', label: 'Angor tumani' },
    { id: 'bandixon', label: 'Bandixon tumani' },
    { id: 'boysun', label: 'Boysun tumani' },
    { id: 'denov', label: 'Denov tumani' },
    { id: 'jarqorgon', label: "Jarqo'rg'on tumani" },
    { id: 'muzrabot', label: 'Muzrabot tumani' },
    { id: 'oltinsoy', label: 'Oltinsoy tumani' },
    { id: 'qiziriq', label: 'Qiziriq tumani' },
    { id: 'qumqorgon', label: "Qumqo'rg'on tumani" },
    { id: 'sariosiyo', label: 'Sariosiyo tumani' },
    { id: 'sherobod', label: 'Sherobod tumani' },
    { id: 'shurchi', label: 'Shurchi tumani' },
    { id: 'termiz_t', label: 'Termiz tumani' },
    { id: 'uzun', label: 'Uzun tumani' },
  ],
  toshkent_v: [
    { id: 'nurafshon', label: 'Nurafshon shahri' },
    { id: 'olmaliq', label: 'Olmaliq shahri' },
    { id: 'angren', label: 'Angren shahri' },
    { id: 'bekobod_sh', label: 'Bekobod shahri' },
    { id: 'chirchiq', label: 'Chirchiq shahri' },
    { id: 'bekobod_t', label: 'Bekobod tumani' },
    { id: 'boka', label: "Bo'ka tumani" },
    { id: 'bostonliq', label: "Bo'stonliq tumani" },
    { id: 'chinaz', label: 'Chinaz tumani' },
    { id: 'oqqorgon', label: "Oqqo'rg'on tumani" },
    { id: 'ortachirchiq', label: "O'rtachirchiq tumani" },
    { id: 'parkent', label: 'Parkent tumani' },
    { id: 'piskent', label: 'Piskent tumani' },
    { id: 'qibray', label: 'Qibray tumani' },
    { id: 'quyichirchiq', label: 'Quyichirchiq tumani' },
    { id: 'toshkent_t', label: 'Toshkent tumani' },
    { id: 'yangiyol', label: "Yangiyo'l tumani" },
    { id: 'zangiota', label: 'Zangiota tumani' },
  ],
  qoraqalpoq: [
    { id: 'nukus_sh', label: 'Nukus shahri' },
    { id: 'amudaryo', label: 'Amudaryo tumani' },
    { id: 'beruniy', label: 'Beruniy tumani' },
    { id: 'chimboy', label: 'Chimboy tumani' },
    { id: 'ellikqala', label: 'Ellikqala tumani' },
    { id: 'kegeyli', label: 'Kegeyli tumani' },
    { id: 'moynoq', label: "Mo'ynoq tumani" },
    { id: 'nukus_t', label: 'Nukus tumani' },
    { id: 'qanlikol', label: "Qanliko'l tumani" },
    { id: 'qoraozak', label: "Qorao'zak tumani" },
    { id: 'qongirot', label: "Qo'ng'irot tumani" },
    { id: 'shumanay', label: 'Shumanay tumani' },
    { id: 'taxtakopir', label: "Taxtako'pir tumani" },
    { id: 'tortkol', label: "To'rtko'l tumani" },
    { id: 'xojayli', label: "Xo'jayli tumani" },
  ],
};
